#!/bin/sh

get_clips() {
	command -v cliphist >/dev/null 2>&1 || printf '%s\n' "cliphist not found"
	command -v wl-copy >/dev/null 2>&1 || printf '%s\n' "wl-copy not found"
	tmp_dir="${TMPDIR:-/tmp}/cliphist"
	mkdir -p "$tmp_dir"
	while IFS= read -r line; do
		info=${line%%'	'*}
		data=${line#*'	'}
		case "$data" in
			*'[[ binary data '[[:digit:]]*\ *B\ png' '[[:digit:]]*x[[:digit:]]*' ]]')
				icon="$tmp_dir/$info.png"
				if ! [ -f "$icon" ]; then
					cliphist decode "$info" > "$icon"
				fi
			;;
			'gimp xcf v'[[:digit:]]*'gimp-comm'*)
				icon='gimp'
			;;
			*' <!-- Created with Inkscape (http://www.inksca'*)
				icon='inkscape'
			;;
			*)
				icon=''
			;;
		esac
		printf '%s\000icon\037%s\037info\037%s\n' "$data" "$icon" "$info"
	done <<EOF
$(cliphist list)
EOF
}

case ${ROFI_RETV:-0} in
	0)
		get_clips
	;;
	1)
		cliphist decode "${ROFI_INFO}" | wl-copy
		exit 0
	;;
	*)
		printf '%s\n' "${ROFI_INFO}" | cliphist delete
		get_clips
	;;
esac
